require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Naming/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
